
export class Fish {
    constructor(species, water_temp_min, water_temp_max, ph_min, ph_max, incompatible_with, size, min_tank_size, schooling, schooling_min,
        tank_position, special_message, water_hardness_min, water_hardness_max) {
        this.species = species
        this.water_temp_min = water_temp_min
        this.water_temp_max = water_temp_max
        this.ph_min = ph_min
        this.ph_max = ph_max
        this.incompatible_with = incompatible_with
        this.size = size
        this.min_tank_size = min_tank_size
        this.schooling = schooling
        this.schooling_min = schooling_min
        this.special_message = special_message
        this.tank_position = tank_position
        this.water_hardness_min = water_hardness_min
        this.water_hardness_max = water_hardness_max
    }
}

export const fishData = {
    'Betta Male': {
        species: 'Betta Male',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 6,
        ph_max: 8,
        incompatible_with: ['Dwarf Gourami', 'Cherry Shrimp', 'Bamboo Shrimp', 'Ghost Shrimp', 'Blue Velvet Shrimp',
            'Crystal Red Shrimp', 'Red Rili Shrimp', 'Tiger Shrimp',
        ],
        size: 2.5,
        min_tank_size: 1,
        schooling: false,
        schooling_min: 0,
        special_message: 'Caution, it is suggested that Male Bettas should not be with other Betta Males',
        tank_position: 'Top Dweller',
        water_hardness_min: 2,
        water_hardness_max: 10,
    },
    'Betta Female': {
        species: 'Betta Female',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 6,
        ph_max: 8,
        incompatible_with: ['Dwarf Gourami', 'Cherry Shrimp', 'Bamboo Shrimp', 'Ghost Shrimp', 'Blue Velvet Shrimp',
            'Crystal Red Shrimp', 'Red Rili Shrimp', 'Tiger Shrimp',],
        size: 2.5,
        min_tank_size: 1,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Top Dweller',
        water_hardness_min: 2,
        water_hardness_max: 10,
    },
    'Cherry Shrimp': {
        species: 'Cherry Shrimp',
        water_temp_min: 62,
        water_temp_max: 82,
        ph_min: 6.5,
        ph_max: 8.5,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.1,
        min_tank_size: 1,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Bottom Dweller',
        water_hardness_min: 5,
        water_hardness_max: 15,
    },
    'Dwarf Gourami': {
        species: 'Dwarf Gourami',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 6,
        ph_max: 8,
        incompatible_with: [],
        size: 2.3,
        min_tank_size: 10,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 5,
        water_hardness_max: 20,
    },

    'Neon Tetra': {
        species: 'Neon Tetra',
        water_temp_min: 72,
        water_temp_max: 76,
        ph_min: 4,
        ph_max: 7.5,
        incompatible_with: [],
        size: 1.2,
        min_tank_size: 10,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 2,
        water_hardness_max: 10,
    },
    'Cardinal Tetra': {
        species: 'Cardinal Tetra',
        water_temp_min: 73,
        water_temp_max: 84,
        ph_min: 4,
        ph_max: 7.5,
        incompatible_with: [],
        size: 1.4,
        min_tank_size: 20,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 1,
        water_hardness_max: 10,
    },
    'African Dwarf Frog': {
        species: 'African Dwarf Frog',
        water_temp_min: 68,
        water_temp_max: 82,
        ph_min: 6.5,
        ph_max: 7.8,
        incompatible_with: [],
        size: 1,
        min_tank_size: 15,
        schooling: true,
        schooling_min: 2,
        special_message: 'Caution, it is suggested that African Dwarf Frogs need a tank with water depth of less than 18 inches because they go up for air',
        tank_position: 'Bottom Dweller',
        water_hardness_min: 12,
        water_hardness_max: 15,
    },
    'Fancy Guppy': {
        species: 'Fancy Guppy',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 6.5,
        ph_max: 8.5,
        incompatible_with: [],
        size: 1.2,
        min_tank_size: 10,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 5,
        water_hardness_max: 15,
    },
    'Harlequin Rasbora': {
        species: 'Harlequin Rasbora',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 6,
        ph_max: 7.5,
        incompatible_with: [],
        size: 1,
        min_tank_size: 10,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 3,
        water_hardness_max: 10,
    },
    'Amano Shrimp': {
        species: 'Amano Shrimp',
        water_temp_min: 65,
        water_temp_max: 84,
        ph_min: 6.5,
        ph_max: 8,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.5,
        min_tank_size: 1,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Bottom Dweller',
        water_hardness_min: 4,
        water_hardness_max: 15,
    },
    'Nerite Snail': {
        species: 'Nerite Snail',
        water_temp_min: 65,
        water_temp_max: 85,
        ph_min: 6.5,
        ph_max: 8.5,
        incompatible_with: [],
        size: 0.05,
        min_tank_size: 1,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: null,
        water_hardness_min: 6,
        water_hardness_max: 10,
    },
    'Black Neon Tetra': {
        species: 'Black Neon Tetra',
        water_temp_min: 68,
        water_temp_max: 82,
        ph_min: 5.5,
        ph_max: 7,
        incompatible_with: [],
        size: 1,
        min_tank_size: 10,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 4,
        water_hardness_max: 8,
    },
    'Congo Tetra': {
        species: 'Congo Tetra',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 6,
        ph_max: 7.5,
        incompatible_with: [],
        size: 2.3,
        min_tank_size: 30,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 4,
        water_hardness_max: 12,
    },
    'Ember Tetra': {
        species: 'Ember Tetra',
        water_temp_min: 73,
        water_temp_max: 84,
        ph_min: 5,
        ph_max: 8,
        incompatible_with: [],
        size: 0.6,
        min_tank_size: 10,
        schooling: true,
        schooling_min: 6,
        special_message: null,
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 5,
        water_hardness_max: 17,
    },
    'Bamboo Shrimp': {
        species: 'Bamboo Shrimp',
        water_temp_min: 73,
        water_temp_max: 84,
        ph_min: 6.3,
        ph_max: 7.7,
        incompatible_with: [],
        size: 5,
        min_tank_size: 20,
        schooling: false,
        schooling_min: 0,
        special_message: 'Caution, it is suggested that Bamboo shrimp have a strong water flow and a specific diet',
        tank_position: 'Bottom-Level Dweller',
        water_hardness_min: 3,
        water_hardness_max: 11,
    },
    'Ghost Shrimp': {
        species: 'Ghost Shrimp',
        water_temp_min: 72,
        water_temp_max: 82,
        ph_min: 7,
        ph_max: 8,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.3,
        min_tank_size: 4,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Bottom-Level Dweller',
        water_hardness_min: 3,
        water_hardness_max: 15,
    },
    'Blue Velvet Shrimp': {
        species: 'Blue Velvet Shrimp',
        water_temp_min: 62,
        water_temp_max: 80,
        ph_min: 6.5,
        ph_max: 7.8,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.2,
        min_tank_size: 4,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Bottom-Level Dweller',
        water_hardness_min: 2,
        water_hardness_max: 16,
    },
    'Crystal Red Shrimp': {
        species: 'Crystal Red Shrimp',
        water_temp_min: 66,
        water_temp_max: 80,
        ph_min: 6,
        ph_max: 7.4,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.2,
        min_tank_size: 4,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Bottom-Level Dweller',
        water_hardness_min: 3,
        water_hardness_max: 7,
    },
    'Red Rili Shrimp': {
        species: 'Red Rili Shrimp',
        water_temp_min: 70,
        water_temp_max: 81,
        ph_min: 6.3,
        ph_max: 7.7,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.2,
        min_tank_size: 4,
        schooling: true,
        schooling_min: 3,
        special_message: null,
        tank_position: 'Bottom-Level Dweller',
        water_hardness_min: 3,
        water_hardness_max: 9,
    },
    'Tiger Shrimp': {
        species: 'Tiger Shrimp',
        water_temp_min: 66,
        water_temp_max: 80,
        ph_min: 6.3,
        ph_max: 8,
        incompatible_with: ['African Dwarf Frog'],
        size: 0.25,
        min_tank_size: 4,
        schooling: false,
        schooling_min: 0,
        special_message: null,
        tank_position: 'Bottom-Level Dweller',
        water_hardness_min: 4,
        water_hardness_max: 7,
    },
    'Silver Angelfish': {
        species: 'Silver Angelfish',
        water_temp_min: 73,
        water_temp_max: 85,
        ph_min: 6.5,
        ph_max: 7.9,
        incompatible_with: ['Fancy Guppy'],
        size: 12,
        min_tank_size: 50,
        schooling: false,
        schooling_min: 0,
        special_message: 'Caution, Silver Angelfish might need tropical freshwater',
        tank_position: 'Mid-Level Dweller',
        water_hardness_min: 3,
        water_hardness_max: 8,
    }
};